<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="D20Tek.Notepad.ViewModel.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\D20Tek.Notepad.Core\D20Tek.Notepad.Core.csproj" />
  </ItemGroup>

</Project>
